version: 0.2

env:
  variables:
    APP_NAME: "sample-java-app"
  # parameter-store:
  #   DB_PASSWORD: "/prod/db/password"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo dnf install -y nodejs


  pre_build:
    commands:
      - echo "Running unit tests..."
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 060152177661.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker --version
      - node --version


  build:
    commands:
      - echo "Building the application..."
      - make image
      - docker images

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - make push 060152177661.dkr.ecr.ap-northeast-1.amazonaws.com

# artifacts:
#   files:
#     - target/*.jar
#   discard-paths: yes
